apiVersion: apps/v1 
kind: Deployment
metadata:
  name: banking-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: test-web
        image: muralisocial123/nodeapp-transcation-history:latest
        ports:
        - containerPort: 3000
